debug: ${DEBUG:true}

server:
  port: ${PORT:8888}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATASOURCE_URL:postgresql://localhost:5432/optione}
    username: ${DB_USERNAME:optione_user}
    password: ${DB_PASSWORD:optione_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${DEBUG:true}
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: 'localhost:9092'

origin: ${ORIGIN:http://localhost:${server.port}}