server:
  port: ${PORT:8888}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATASOURCE_URL:postgresql://localhost:5432/cipher_pass}
    username: ${DB_USERNAME:cipher_pass_user}
    password: ${DB_PASSWORD:cipher_pass_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: 'localhost:9092'
