server:
  port: ${PORT:8888}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/leetcode_clone
    username: leetcode_clone_user
    password: leetcode_clone_password
    # driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/leetcode_clone
    # username: leetcode_clone_user
    # password: leetcode_clone_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: 'localhost:9092'
