name: Build and Deploy JARs

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: opti-one/judge
          path: judge
      - uses: actions/checkout@v3
        with:
          repository: opti-one/code_executor
          path: code_executor

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build judge
        run: |
          cd judge
          ./gradlew bootJar

      - name: Build code_executor
        run: |
          cd code_executor
          ./gradlew bootJar

      - name: Create deploy branch
        run: |
          git checkout -b deploy

      - name: Copy JAR files to deploy branch
        run: |
          cp judge/build/libs/*.jar deploy/
          cp code_executor/build/libs/*.jar deploy/

      - name: Commit and push deploy branch
        run: |
          git add .
          git commit -m "Built JARs and created deploy branch"
          git push origin deploy
